# Generated by Django 2.2.7 on 2019-12-10 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='course',
            name='selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.TextField(max_length=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='courseRating',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
        migrations.AlterField(
            model_name='course',
            name='difficulty',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='profRating',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
