# Generated by Django 2.2.7 on 2019-12-10 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191209_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='courseRating',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
        migrations.AlterField(
            model_name='course',
            name='difficulty',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
        migrations.AlterField(
            model_name='course',
            name='profRating',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
