# Generated by Django 2.2.7 on 2019-12-10 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191210_0204'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
